# Generated by Django 2.2.4 on 2020-03-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link5', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='resourceAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('rType', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('sum_click', models.IntegerField(default=1)),
            ],
        ),
    ]
